name: CI + CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
      - name: Fail
        run: exit 1

